---
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: lastmod
  label: Lastmod
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- name: keywords
  label: Keywords
  type: list
  hidden: false
  default: []
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: []
- name: author
  label: Author
  type: text
  hidden: false
  default: ''
- name: comment
  label: Comment
  type: boolean
  hidden: false
  default: false
- name: toc
  label: Toc
  type: boolean
  hidden: false
  default: false
- name: autoCollapseToc
  label: Autocollapsetoc
  type: boolean
  hidden: false
  default: false
- name: contentCopyright
  label: Contentcopyright
  type: boolean
  hidden: false
  default: false
- name: reward
  label: Reward
  type: boolean
  hidden: false
  default: false
- name: mathjax
  label: Mathjax
  type: boolean
  hidden: false
  default: false
